/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./src/**/*.{html,js,jsx,ts,tsx}"],
    theme: {
        extend: {},
        colors: {
            primaryColor: "#7FF5E0",
            ligth10: "#E5F7F7",
            light20: "#CCEFEF",
            light60: "#66D0CE",
            light100: "#00B0AD",
            default: "#0F0F0F",
            descripton: "#CCEFEF",
            gray: "#E9ECEF",
            white: "#FFFFFF",
            pink: "#f5d9d9",
            gray2: "#afb7c0",
            index1: "#cfe5da",
            index2: "#262a4e",
            slide1: "#ff80e3",
            slide2: "#fae639",
            slide3: "#a84b4b",
            slide4: "#b2aee1",
            slide5: "#9fc2b6",
            slide6: "#8aa84b",
            text1: "#8EF8FF",
            text2: "#DFF4FF",
            text3: "#DEFFB4",
            black: "#000000",
            profileGray: "#D9D9D9",
            dashboardGray: "#9FA9B3",
        },
    },
    plugins: [],
};
